name: loft_generator
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: rafal.wachol <email@example.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  source_gen:
  code_builder:
  build:
  analyzer:
  recase:
 
  loft:
    path: '../loft'

dev_dependencies:
  build_runner:
  build_test:
  test: ^1.0.0
